[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid


; ==============================
; PHP-FPM
; ==============================

[program:php-fpm]
command=php-fpm -F
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=3
priority=5


; ==============================
; NGINX
; ==============================

[program:nginx]
command=sh -c "sleep 2 && nginx -g 'daemon off;'"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=3
priority=10


; ==============================
; Laravel Queue Worker
; ==============================

[program:laravel-queue]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=15


; ==============================
; Laravel Scheduler
; ==============================

[program:laravel-scheduler]
command=sh -c "while true; do php /var/www/html/artisan schedule:run --verbose --no-interaction && sleep 60; done"
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
